config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/pages', to: 'pages#home'

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, :list, presence: true
  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookmarks/new.html.erb
<div class="container mt-3">
  <h1>Add movie</h1>
  <%= simple_form_for [ @list, @bookmark ] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit "Create", class: "btn btn-primary mb-3" %>
  <% end %>
  <p><%= link_to "Go back", list_path(params[:list_id]) %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Your Movie Playlists</title>
    <link rel="icon" href="https://img.icons8.com/plasticine/2x/popcorn.png">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container mt-3">
  <h1>Movie lists</h1>
  <div class="cards">
    <% @lists.each do |list| %>
      <%= link_to(list_path(list), {class: "no-text-decoration"}) do %>
        <div class="card-category grow mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : image_path('pexels-cottonbro-3945317.jpg') %>)">
          <%= list.name %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= link_to "New list", new_list_path, class: "btn draw-border mt-3" %>
</div>

app/views/lists/new.html.erb
<div class="container mt-3">
  <h1>New List</h1>
  <%= simple_form_for [@list] do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Create", class: "btn draw-border my-3" %>
  <% end %>
  <%= link_to "Go back", lists_path, class: "no-text-decoration mt-3" %>
</div>

app/views/lists/show.html.erb
<div class="container mt-3">
  <div class="card-category mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @list.photo.attached? ? cl_image_path(@list.photo.key) : image_path('pexels-cottonbro-3945317.jpg') %>)">
    <%= @list.name %>
  </div>
  <% @list.bookmarks.each do |bookmark|%>
    <div class="card-product mb-3">
      <%= image_tag bookmark.movie.poster_url%>
      <div class="card-product-infos">
        <h2><%= bookmark.movie.title %></h2>
        <p><%= bookmark.comment %></p>
        <%= link_to 'Delete', bookmark_path(bookmark), class: "no-text-decoration", method: :delete, data: { confirm: 'Delete this movie?' } %>
      </div>
    </div>
  <% end %>
  <%= link_to "Add Movie", new_list_bookmark_path(@list), class: "btn draw-border mb-3"%>
  <%= link_to "Go back", lists_path, class: "no-text-decoration m-3" %>
</div>

app/views/pages/home.html.erb
<%= link_to(lists_path) do %>
  <div class="sign">
    <span class="fast-flicker">E</span>NT<span class="flicker">E</span>R
  </div>
<% end %>